<a href="https://colab.research.google.com/github/Esteban191/upgraded-goggles/blob/main/apuestas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df_apuestas=pd.read_csv("/content/drive/MyDrive/mauro_apuestas/apuestas-ene-feb-mar-2023-compilado (1).csv")

In [5]:
df_apuestas.shape

(194, 10)

In [4]:
df_apuestas

,LIG,CUO,PARTIDO,COMBO 1,COM 2,RES,TE.x.EQ,TTE,Unnamed: 8,Unnamed: 9
0,ESP,1.36,Athletic Bilbao - Real Madrid,DOV + -4.5,NaN,0X2,12-2,14.0,NaN,NaN
1,ITA,1.45,Juventus - Atalanta,H2L + -11.5,NaN,3X3,6-4,10.0,NaN,NaN
2,ITA,1.26,Spezia - Roma,DOV + -4.5,NaN,0X2,4-0,4.0,NaN,NaN
3,ING,1.62,Arsenal - Manchester United,DOL + -12.5,NaN,3X2,12-4,16.0,LOST TE +12.5,NaN
4,ESP,1.34,FC Barcelona - Getafe,GL + 1.5,NaN,1X0,4-2,6.0,LOST GOLES -1.5,NaN
...,...,...,...,...,...,...,...,...,...,...
189,EUR,1.33,FC Union Berlin - Ajax,DOL,NaN,3X1,6-4,10.0,NaN,NaN
190,EUR,1.38,AS Mónaco - Bayer Leverkusen,DOL,NaN,2X3,6-5,11.0,LOST GV,"El local jugo muy mal, y se confió porque gana..."
191,LIB,1.45,Cerro Porteño - Curicó Unido,GL,NaN,1X0,9-3,12.0,NaN,NaN
192,LIB,1.40,Sporting Cristal - Nacional Asunción (PAR),H2V,NaN,5X1,6-1,7.0,LOST GL,"Demasiada buena cuota a un H2V, El visitante a..."
193,URU,1.32,CA Huracan - CA Boston River,GL,NaN,1X0,6-5,11.0,NaN,NaN